project:
  type: website
  output-dir: docs

resources:
  - CNAME


website:
  title: "Matthew Lavallee"
  site-url: "https://www.mplavallee.com"
  repo-url: "https://github.com/MatthewLavallee/matthewlavallee.github.io"
  description: "Website of Matthew Lavallee"
  google-analytics: "G-1GWH810RLY"
  twitter-card: 
    creator: "@lavalleemat"  
  search: true
  navbar:
    left:
      - href: files/cv_lavallee.pdf
        text: CV
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Montserrat
    fontsize: 0.95em
    toc: false

editor: visual

page-footer:
    left: |
      {{< fa regular copyright >}} Andreas Handel, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      Opinions are my own and do not represent my employer
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [these folks](/posts/quarto-website-migration.html)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/andreashandel/andreashandelwebsite)